-- MySQL Script generated by MySQL Workbench
-- Wed Feb 21 16:59:20 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vivero
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vivero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vivero` DEFAULT CHARACTER SET utf8 ;
USE `vivero` ;

-- -----------------------------------------------------
-- Table `vivero`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`users` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `active` INT(1) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idusuario`),
  UNIQUE INDEX `cedula_UNIQUE` (`cedula` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`secciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`secciones` (
  `idseccion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `numplantas` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `tempmax` FLOAT NOT NULL,
  `tempideal` FLOAT NOT NULL,
  `tempmin` FLOAT NOT NULL,
  `inicioriego` TIME NULL,
  `finalriego` TIME NULL,
  PRIMARY KEY (`idseccion`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`plantas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`plantas` (
  `idplantas` INT NOT NULL AUTO_INCREMENT,
  `idseccion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fruto` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idplantas`),
  INDEX `fk_plantas_secciones1_idx` (`idseccion` ASC),
  CONSTRAINT `fk_plantas_secciones1`
    FOREIGN KEY (`idseccion`)
    REFERENCES `vivero`.`secciones` (`idseccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`muestras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`muestras` (
  `idmuestra` INT NOT NULL AUTO_INCREMENT,
  `idseccion` INT NOT NULL,
  `humedad` FLOAT NOT NULL,
  `temperatura` FLOAT NOT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`idmuestra`),
  INDEX `fk_muestras_secciones1_idx` (`idseccion` ASC),
  CONSTRAINT `fk_muestras_secciones1`
    FOREIGN KEY (`idseccion`)
    REFERENCES `vivero`.`secciones` (`idseccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`cantidadplantas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`cantidadplantas` (
  `idcantidadplantas` INT NOT NULL AUTO_INCREMENT,
  `idplantas` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `movimiento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcantidadplantas`),
  INDEX `fk_plantas_has_secciones_plantas1_idx` (`idplantas` ASC),
  CONSTRAINT `fk_plantas_has_secciones_plantas1`
    FOREIGN KEY (`idplantas`)
    REFERENCES `vivero`.`plantas` (`idplantas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
